version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - 8080:8080
    expose:
      - '8080'
