import { Inter } from "next/font/google";
import MyApp from "./Provider";
import { ThemeProvider } from "@chakra-ui/react";
import { theme } from "../../styles/theme";
import { SessionProvider } from "next-auth/react";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="pt">
        <head>
          <title>Thiago - blog</title>
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
}
